apiVersion: v1
kind: ServiceAccount
metadata:
  name: lauraforloveland
  labels:
    app.kubernetes.io/name: lauraforloveland
    app.kubernetes.io/instance: lauraforloveland
    app.kubernetes.io/version: "1.16.0"