apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buyveteranproducts
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - obso.ninja
    secretName: buyveteranproducts-tls
  rules:
  - host: obso.ninja
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: buyveteranproducts
            port:
              number: 80

