apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: buyveteranproducts.com
  labels:
    app.kubernetes.io/name: buyveteranproducts.com
    app.kubernetes.io/instance: buyveteranproducts.com
    app.kubernetes.io/version: "1.16.0"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - "obso.ninja"
      secretName: buyveteranproducts.com-tls
  rules:
    - host: "obso.ninja"
      http:
        paths:
          - path: /
            backend:
              serviceName: buyveteranproducts.com
              servicePort: 80