apiVersion: v1
kind: ServiceAccount
metadata:
  name: buyveteranproducts
  labels:
    app.kubernetes.io/name: buyveteranproducts
    app.kubernetes.io/instance: buyveteranproducts
    app.kubernetes.io/version: "1.16.0"