apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: patriotsweepstakes
spec:
  tls:
  - hosts:
      - patriotsweepstakes.com
    secretName: patriotsweepstakes-tls
  rules:
  - host: patriotsweepstakes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: patriotsweepstakes
            port:
              number: 80
