apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: patriotsweepstakes
  labels:
    app.kubernetes.io/name: patriotsweepstakes
    app.kubernetes.io/instance: patriotsweepstakes
    app.kubernetes.io/version: "1.16.0"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - "patriotsweepstakes.com"
      secretName: patriotsweepstakes-tls
  rules:
    - host: "patriotsweepstakes.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: patriotsweepstakes
              servicePort: 80