apiVersion: v1
kind: ServiceAccount
metadata:
  name: patriotsweepstakes
  labels:
    app.kubernetes.io/name: patriotsweepstakes
    app.kubernetes.io/instance: patriotsweepstakes
    app.kubernetes.io/version: "1.16.0"