apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps
    chart: external-dns
    helm:
      valueFiles:
        - external-dns-values.yaml
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.4.x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
