apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: external-dns
    helm:
      parameters:
      - name: "provider"
        value: digitalocean
      - name: "digitalocean.secretName"
        value: digitalocean-api-token
      valueFiles:
        - external-dns-values.yaml
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.4.x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
