apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: ingress-nginx
    helm:
      values: |
        pushgateway:
          enabled: false
        controller:
          publishService:
            enabled: true
        controller:
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/port: "10254"
                prometheus.io/scrape: "true"
            serviceMonitor:
              enabled: true
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.1.x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
