apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lightfamily.photos
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: manifests/lightfamily.photos
    repoURL: https://github.com/awbsough/obso-ninja-k8s-argocd.git 
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true