apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://jp-gouin.github.io/helm-openldap/
    targetRevision: 2.0.4
    chart: openldap
    helm:
      values: |
        persistence:
          enabled: false     

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
