apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: sealed-secrets
    helm:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: v0.16.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
