argo-cd:
  installCRDs: false
  global:
    image:
      tag: latest
  dex:
    enabled: false
  server:
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
    
    ingress:
      enabled: true

      hosts:
        - argocd.obso.ninja
      
      paths:
        - /
      
      pathType: Prefix

      tls:
        - secretName: argocd-tls-certificate
          hosts:
            - argocd.obso.ninja
