argo-cd:
  installCRDs: false
  global:
    image:
      tag: latest
  dex:
    enabled: false
  server:
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm

      oidc.config: |
        name: Auth0
        issuer: https://dev-b5cremok.us.auth0.com/
        clientID: C5BSIoPy0ir0IHfYLAx7LZvmqofXK5HS
        clientSecret: $argocd-auth0-secret:clientSecret
        requestedIDTokenClaims:
          groups:
            essential: true
        requestedScopes:
          - openid
          - profile
          - email
          - 'https://argocd.obso.ninja/claims/groups'

    rbacConfig:
      policy.csv: |
        g, argo-admins, role:admin

      policy.default: role:readonly
      scopes: "[https://argocd.obso.ninja/claims/groups, email]"

    ingress:
      enabled: true

      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

      hosts:
        - argocd.obso.ninja

      paths:
        - /

      pathType: Prefix

      tls:
        - secretName: argocd-tls-certificate
          hosts:
            - argocd.obso.ninja

      https: true
