apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: chilson
spec:
  jobTemplate:
    metadata:
      name: chilson
    spec:
      template:
        metadata:
        spec:
          containers:
            - image: ghcr.io/awbsough/chilson-autoregister:main
              name: chilson
              imagePullPolicy: Always
              env:
                - name: USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: chilson-username
                      key: username
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: chilson-password
                      key: password
          imagePullSecrets:
            - name: githubsecret
          restartPolicy: OnFailure
  schedule: 1 6 * * *
