apiVersion: v1
data:
  clientSecret: RGlfVDJUd1A0a1lQbmZ0UnlFYlVhSXF2Q2d5QTFkbDlMZHJfbGlKMXJmUHFSZl9yZG1MbGVFSGtkNElidUw4ag==
kind: Secret
metadata:
  creationTimestamp: null
  name: argocd-auth0-secret
