apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    clientSecret: AgC+fRZMDTtqS5hdk9TX2xqtxap68bh/eiHKt6v2qVjbnv8aPHQG1xmVGsAh4N9UEX/GpVOONmq1aVdWRGWIWvjywOx0hpMXD9KtOWuVsLZWHbIKcz3jvm/8k/tXgl5NWu+crLFnSAGIPOwY1/+c1Tn6Ye/5MsotdkhOZBZ08czPnntP8PKZABGaWlP1a+S+dXGxT26bOc/dtfFbj4RbSEZFiSiYokAV/z+M1WlRlGoEEOCe4fgOeqp3/sAjjN1w5rcm/SMbkQ01qa2d69NkOEmTBYbK/wH90f4o41kTkIWkF70UbdrglIVvwTM5x1UyoHUZLBoUudzuRPEEWnd0PAe/FN3hrio+3syawFosjg+fofJypai7m/NBTlbaUkZDcNRZyden7euFftuQhd27jb44kJfrpEOuEdxxda43xEck1H6jE8j1zTcSvYhyo7JRTy5txS6k7CJpYBQdL1sp/Ndps+6RX0449jR1YPPlQcxV/yZ+V9nbd2kFyc5N2P7AePheR9T46lxqdb9fY1LaE7LJivVaJcmXIvAJHH2Ozr7HvNCPNx/EFvaZVIafNk9dllAHQ0hZNzyKDRUnq4XcfUAKyM15Fw+3MHWkOfEXi+2MSOSD9JiIxx8iJuCutT3YwUoEnttZv9iLdKJ4ic3hDp201h8db3GQr+f+N9ciTDtli441cJF3cr8l06f5RzLx2aIRW/T81MmfcCZmi1s/PX7ONdpL7ZjDykLnhB6nNJxh2QcYutQe8IyVy8QynfIeUclqky0C2OTLpLaCOFMxES3ItkRuulF5d/v9SNTTvg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

