apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    auth0.txt: AgBjIBIIgblfnF7FtjgV/XSPpSCWEIyMqtnnuoHFZPSB9uemha31kNB5yk4OMpxWIWvo6kd5kl3/iCwX6PUHmNOXOksJxHHPWN4g36HBDX4RbSdxm7IyF3zdPICDBFp06HEEbPkCB9FmOzTpV7m3wIX0FNiJk4WLOcVnRx6n8Ql4b2ukggmlml2gYRBDV/uj6JbZT1hhJwC0ZAQTIE29Mr27JEgzySvlhrK6H1N/WQlt8pfkSnWglhW44wSH40Vg2zuswmBLgkMes8L/8BEtN6rtUSqLy18K24VByRrWXlN+g/DLoVEPBmjjfTBpEt/4IQrwPCV8/ST0fY0SqlJGl8rAY/EQ/8uB/+xwLiWkyVeksRJScjSgGOjX+6NHJmIYvtmXLnid738j0HQ44mznJIbBpe4JTGKB4S2Ayz0aEIFv/vx5yWlzjfevv+K88fShIhfOvVxJ/jFSnpCgJZwRBElzShzJccvqAylGDeAHnzgc3eZeTY0nHHzt9+l18PGMjmCg0CG0Js6iShbEegml2gobqfQaFlZgjGQ5Ton4fM7mP9cpoL8crvfHQdCH0YfIHCCiEDDcEN1smJzp6bpqnf900rpVASO2CYL0VkZlsNH16BGRjGraZHuq1B8tTyREzu37DBnBo4Oh5m2dZt4GbELDA2UdUZDDfK36PQKpb2p+q1Kal6yir4u1t6FQBm+2x8kTwfs6ApAlyQjpH3myb8yQGZW1RIPrchX5uNr29hvbpn4IZ0YwiKryK+Dt20xgMOUP5eBRcXWqxZ+m3DoQCr18
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

