apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCaJ6GCqUrWwAD9d2egGeFX6rRZ/PS+seKumkfQQF4qJhhQ2jxzOs+GuewaQA7Yjjq5AjNIlJ5xVw0Qo3a8EANj/P3FDuxqRTws8Rvpeo31z1X4qRFZuuUiqhP54QtB5sALehFoOKLUjGwoKnuKyb1TUnZ+43zPkuqC6RadDy3m1DEXRCL0DqyGFv3HtB8QTObD95TP7rWmxnvuIYsIn+3l3K/pBuMoQSvBY6rRFDcIgylM+BLu/lWMHlt/zQ2rRL8wVJeheOkG0IZcAsDR71R54JH+nDmRXs1A7aRPD5Ii3GNMxVP4YxhejEU03XQL6nhIOD6ywd10exyGeESvXPUTYsiTa1i7WRafAg/QRXThOyiufUjZCS6k2sLGd2OgsmBBEd0YeTjEsZ3GQppvMr6icG/6CC4XGBbJTcOmHyYjzYV9qMzgyD4ItiWQgz1pyAgaSKFTsE274kw52fmqjEM/+ECkAdFA3TiaH1GMpwd8/bkAjfRlCZbsMgcnhSblm5mVTLd05DsStkLPxY+g1RtgWcviiUtXCIHVqqTiDpmmgvXFRb+3AFROIIZOoD8rjHrIc7dOirHkGSNw2Bv49zhyhQPXYUQne6beH80PZ+5jn/VqFZcaBn3URXgEV2IyQ0DTO/lX9O5h3ge6Xeqg88CstKxcOgCrd6f7M/qShUrhNhBl+zj7zFcvQtdzZKE7D+x/ksjSx0msRCJHlwa2stCz5U+4hZkPeRDgXRfzJWX63A7nfeT4YPig96FsdwH+4NICW3iE+JFcgiElpA0ft0acARyymSN/d0PNyCWaUGiY48z/qnUdFlM3kk45xK/euB0/soANYGOPGqLYrPzoeb/nICkkJmDH9TkAmTQs
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: default

