apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: githubsecret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBrdcROQ3zaBWBPUnq4KzNyFGvz+uC8zShLgOdjtJrnuPFKUIy0IDO0eNPZMdeZmUl7Tyhb+MI4KWkbpaAK/nCH9rfKGOT6OQkQg38/uR4HU2DxIKjQ89PI3E3CwIMSJs6s5+LJRLHayJ0lecoAcYF9Z6/HAp4T1rwecOoTIeewM21a9O4aZcrw9xU/onKz9IIwcSsfsGJQvmuH9RMqnPuXv4nTBq+CSrjb2y5BMo87ina3uxeJvYzns4WjVtcAcR4YeMysKTT5MsCUTf0rCE+MCjpUYcyc6gWoi6yJ/XSkEc5kxaGGPPG+Cc5BAsCm9zz696NkSOBgw6kTmYpg4czrSw3hFhSMSoUX6fjv+zbeF8gEHrnITsXe8xJydcTDZNmpxhnSOMam9LVZyMhA3/PBO3+GUXmusWi8WGNYYjMRPULXOtx2pKWYHHPOpev0YIv0+HVDcFlASnfcWl5AcmQ+3xNZR4IXZhMe/buvzIckW2CqzuDFfEVmvE9cKdpAwaIFuva/aGSAobErI64zgb/pE4SRkWaybENtIsF9M7zzjVs1h2H0IQIDkFapu4kjh1yhTaYEhbHGTTmI4k+CSVSgN1lPW6lQI/I7nFUlqA0X2y5E2TISthABj0sPVtTCKnbq4w3iVcMzCQekBEa3gKWefPIQcJYbJoBph/e7bE8/0tB+y+n6bm0LlKybbkvQIh5rgRNlwDWwCHD3UTaKn6GM8tUXSeKmfnct7EGgXFZuo8C9E6XyrIv8BM/I1HdHPyCt+OOmnwXEbOMvaHAdd8aBrobhVI/ArAaZNjzZcW9PI8Yfs+zGyIM8laxr404QC0+UBkCNTA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app: app-name
      name: githubsecret
      namespace: default
    type: kubernetes.io/dockerconfigjson

