apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: githubsecret
  namespace: default
spec:
  encryptedData:
    .dockerconfig.json: AgAGZkjmYGFYXygxJ2GQKbzk4WKMCE1j7lRk3Z7Y+CBU3CqxLFCOVWX0bAew2y0B3lcGyID2a34HU/5Vo6XMFfooqNP2a0CW5/JQaqwqBVOtGe5uTw3QU7wjhxYvrT4As/4VQv2Zpb7qA4k1RWg2ITACTpyMJEhdgHhmeXS7zjoAvRGxBrF3CfGk63DSPd8vydqPJ80IGgJAt9O7Cs5ssjUGunjCNseVwKYtp8zgaoOr+n8dDY8s0kxu14W4S8MNht5ATYtGYH5tg2gBzpciJntLTdWRdlWknTybP4RskHgXF9C6sMkhorw4sdKocwHkfa0yXjZDz4SOuj6WFrh/nm32y/glLM3wjqMQ6VWEtPxibBAnwvbdfGOs+H2ZS68DSDdvuHMy5EjBcCGkYxK/5yirsK/Q1jdUr0RZXtdLpy7uGLdwYetEXNo5Iwzr+tbJ00mJfK5dT4f9fX03L7DYeyvWB7aw+pVotLI+cJQor8H9fcVrfJ2S65GtpXW+XGa2Hu+/tNndW940a/2DiYcYqmAqZ2hyAt7obBGbi7+74uRc9Yn1vTVVt1tdv0+8NyPJ8mJFDn3k4mVNnPeedwukMtOLC9M3zdKR5RGgnZaXrjbmSLC8cDDw9OW8Deaogg+UmDxPPpBNNY9nwPXADP2H2q+Y0ixbvMDS2gXoZxC44aXx6ulyHTZV25vpuXs5xSpbovQQd1O9DqZ+Mo3D9JZk1gp6MBZQjzn3WS53Gr2RHJEaQCS7bvXOzIdF7B+bWDfk+Kinqj5DDHB0VO+OKIjUo8MHwNrY0lsyQnxkAXZ/C6U4Drcs+DrrXAbV+yQXph2n8uElT51/MGTgg3LGYrlvS0/QHkP9uFYWa9nhG/f5PwyBGnklxR1iqaNfH9xp51fTZgDLH0A5R8MoktRlJ3mrYy/yAa7AFaq9AfFII6tE+KVcY4oVDR2KLwyVAOrpiPdip9Zo64KTFDzgj5dZNr8CLzBKOkIznjLyuyl0DJ4nKxwLT+s5V2LOkrAsuya8JJ+/ufX9PlNDpCGahnXoa8TfRm0qJvKCrxHCaZDisFxPjzoueLDRHoP88nhcTFn5EL9F8r5G4yOH0E0uacGgHA6GZKSKpSNOx9CR487kya06+1LXPgiXpsis+g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: githubsecret
      namespace: default
    type: kubernetes.io/dockerconfigjson

