apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ldap-admin-password
  namespace: default
spec:
  encryptedData:
    LDAP_ADMIN_PASSWORD: AgChhfYGJkOHkoFkZwDj4IWcWESgSD3GfKANitsGWt2hHjGSPM+2cW+/aNSZQXKe2CQmlHj92uF7Wf+Np6fFgEMEwU/YF9en+X296AYMhpImP57GrJ3v95WYEAWwvfiKOAMuV9U8cnLYqs3atVUzn0kqO5gwP6uv9b65UiwaoBECSK4AL5Naxi0cxKMJYpDMdT71GydvJ15IBLhNjr2Oo0IKG0ixdZd8Ddh5odv1ZY8HhquGRnwgXmgwkggASQ9zT2mkNcyc9VM1XjqQ7f9vVk7CrMAEPjHi1eRXaIskB9P9xVKoI6y5tntF/EhFSlGJRYAwg/wczvhhQab49lDkTDsCTEVWdRdWD9U7yzrRAKPDLmAzeO1m8k6b0mjNPDekw92Jb9cp9V1F7vFOUHSwdgiNPmzYOYfYDAO1iCLvHgVFF8TzYZXKWtulsi3EpwcbfBN8jHpds5KageXYfwUT4k1AXetKcQLYxA71paf4m63EFEm4arXlcikiBDcqko6Bsl1DppzoHhmL15BcBhlyRYuYh4ZzrSYqGyrU+7CtzHYD6JoSxfSfjFlfda+5ZgLrJNY/B5TfthAX3bGTVTUwgulh5wCZI57BV22y+OCSJWyYE/HVxi6FPc4wfbHcSW7yq/MbkdCOexOeZaDfkl+aI1Rn2bXw6tXM+7KSeJVm1qFGDGtlFWJKMS6NYo/MEAV0n1+0GkhgybE0RT8ZWhgV
    LDAP_CONFIG_PASSWORD: AgA/K4xRDYDmo6ERqjjgrEPnmXDemHFMYC2sEXshN8/b5KVgGVuFIT9lql0XjlTug5xAMIewo74klAnhe+WfgBKxajLUyApbu8E/mo6Oc2pOIgcOxMTEdqfWFngZXe35WUuKYkkmKEDohpfjFn2qD68fwVelcAc0MAebdHnFJ3gd/8Iv4leUPQwu5yq8fWDtUJPdbFp7G7XnXX6rjVJNppPYOD72ATNiFayf2xa29ibzoa5/s937nXS7GVGurOG3eWY+/gkW0YhjsdJ9+fDYQdotov/dZQ8vNY2YrBWx1EWhktcmu4Nppo8vf/sh93xuzyPKlk7UwvT1/Kx//HRNJD5ogAs0iW/GCM8OxkSN7RhAryQNj+ipBEUlSec84RjOx2yS+NvwuD9fJOu4OAb6Tr6BrkdrXFwSzLksVU6rbHk6vyQ3+n+D2JQu+vtsSZ8Uh1pDG1hqY786lq975K31twUvvu0+ORFaDuzwINKu+YxjqLKQWtSKUiyS36ttmzrTx4yHS8pp5gT5av9/X3s25uaBmXaDRwpmGhp0Mpt2M4Td9cOYB2ul1+RJSjwluoMVnXbUeYf20QZVznQpeJO1l+1bRnG4xM8qKxZSfs13hvr0AWyfZKSWBpUdN0bjEubWs7IC3Gr2o1u2nFbIYaiuN1mtZg5voZqkn8DLaX/YRpjhh+eNQSonmL19NvYnb5LAINzpu2tIzSm5P2Y=
  template:
    metadata:
      creationTimestamp: null
      name: ldap-admin-password
      namespace: default

